# site settings
title: Pura Vida Divehouse
subtitle: Diving and Accomodation Algarve.
email: youremailaddress@gmail.com
description: Scuba Diving and Lodging in one place. Where people meet, live and share their ideas and exciting experiences.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Rua da Pedra Negra
city: Sagres
state: Baleeira
zip_code: 8650-362
country: Portugal
phone: +351 913210716

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url: https://www.facebook.com/puravidadivehouse
# github_url:
# gitlab_url: 
# googleplus_url: https://plus.google.com/u/0/104538173205622522267
instagram_url: https://www.instagram.com/puravidadivehouse
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/puravidasagres

# build settings
markdown: kramdown

sass:
  style: compressed
